package com.mismaiti

import androidx.compose.ui.graphics.Color

//generated by https://materialkolor.com
//Color palette was taken here: https://coolors.co/palette/e63946-f1faee-a8dadc-457b9d-1d3557

val Seed = Color(0xFFFBEDFF)

val PrimaryLight = Color(0xFF655B6A) // Dark Purple
val OnPrimaryLight = Color(0xFFFFFFFF) // White
val PrimaryContainerLight = Color(0xFF000000) // Black
val OnPrimaryContainerLight = Color(0xFFFFFFFF) // White

val SecondaryLight = Color(0xFF635C65) // Grayish Purple (Gray tone)
val OnSecondaryLight = Color(0xFFFFFFFF) // White
val SecondaryContainerLight = Color(0xFF4A90E2) // Vibrant Blue
val OnSecondaryContainerLight = Color(0xFFFFFFFF) // White

val TertiaryLight = Color(0xFF665A6E) // Muted Purple
val OnTertiaryLight = Color(0xFFFFFFFF) // White
val TertiaryContainerLight = Color(0xFFEEDDF6) // Light Lavender
val OnTertiaryContainerLight = Color(0xFF4E4256) // Dark Grayish Purple

val ErrorLight = Color(0xFFEF4126) // Red
val OnErrorLight = Color(0xFFFFFFFF) // White
val ErrorContainerLight = Color(0xFFFFDAD6) // Light Pink
val OnErrorContainerLight = Color(0xFF410002) // Dark Red

val BackgroundLight = Color(0xFFFFFFFF) // White
val OnBackgroundLight = Color(0xFF1D1B1D) // Almost Black

val SurfaceLight = Color(0xFFFFFFFF) // White
val OnSurfaceLight = Color(0xFF1D1B1D) // Almost Black

val SurfaceVariantLight = Color(0xFFE6E1E3) // Light Grayish Pink
val OnSurfaceVariantLight = Color(0xFF484648) // Dark Gray

val OutlineLight = Color(0xFF797678) // Medium Gray
val OutlineVariantLight = Color(0xFFCAC5C7) // Light Gray
val ScrimLight = Color(0xFF000000) // Black

val InverseSurfaceLight = Color(0xFF323031) // Dark Gray
val InverseOnSurfaceLight = Color(0xFFF5EFF1) // Off-White

val InversePrimaryLight = Color(0xFFCFC2D3) // Light Lavender
val SurfaceDimLight = Color(0xFFDED9DA) // Light Grayish Pink
val SurfaceBrightLight = Color(0xFFFEF8FA) // Light Pinkish White

val SurfaceContainerLowestLight = Color(0xFFFFFFFF) // White
val SurfaceContainerLowLight = Color(0xFFF8F2F4) // Very Light Pink
val SurfaceContainerLight = Color(0xFFF2ECEE) // Light Pinkish Gray
val SurfaceContainerHighLight = Color(0xFFECE7E9) // Very Light Grayish Pink
val SurfaceContainerHighestLight = Color(0xFFE6E1E3) // Light Grayish Pink


val PrimaryDark = Color(0xFFCFC2D3)
val OnPrimaryDark = Color(0xFF352D3B)
val PrimaryContainerDark = Color(0xFF4C4452)
val OnPrimaryContainerDark = Color(0xFFECDEF0)
val SecondaryDark = Color(0xFFCDC3CE)
val OnSecondaryDark = Color(0xFF342E37)
val SecondaryContainerDark = Color(0xFF4B454D)
val OnSecondaryContainerDark = Color(0xFFE9DFEA)
val TertiaryDark = Color(0xFFD1C1D9)
val OnTertiaryDark = Color(0xFF372C3F)
val TertiaryContainerDark = Color(0xFF4E4256)
val OnTertiaryContainerDark = Color(0xFFEEDDF6)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF141314)
val OnBackgroundDark = Color(0xFFE6E1E3)
val SurfaceDark = Color(0xFF141314)
val OnSurfaceDark = Color(0xFFE6E1E3)
val SurfaceVariantDark = Color(0xFF484648)
val OnSurfaceVariantDark = Color(0xFFCAC5C7)
val OutlineDark = Color(0xFF939091)
val OutlineVariantDark = Color(0xFF484648)
val ScrimDark = Color(0xFF000000)
val InverseSurfaceDark = Color(0xFFE6E1E3)
val InverseOnSurfaceDark = Color(0xFF323031)
val InversePrimaryDark = Color(0xFF655B6A)
val SurfaceDimDark = Color(0xFF141314)
val SurfaceBrightDark = Color(0xFF3B383A)
val SurfaceContainerLowestDark = Color(0xFF0F0E0F)
val SurfaceContainerLowDark = Color(0xFF1D1B1D)
val SurfaceContainerDark = Color(0xFF211F21)
val SurfaceContainerHighDark = Color(0xFF2B292B)
val SurfaceContainerHighestDark = Color(0xFF363436)
